// webui/src/routes/StatusTab.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { store } from '../lib/store.svelte';
  import { ICONS } from '../lib/constants';
  import { BUILTIN_PARTITIONS } from '../lib/constants_gen';
  import Skeleton from '../components/Skeleton.svelte';
  import BottomActions from '../components/BottomActions.svelte';
  import './StatusTab.css';
  import '@material/web/progress/linear-progress.js';
  import '@material/web/chips/chip-set.js';
  import '@material/web/chips/filter-chip.js';
  import '@material/web/iconbutton/filled-tonal-icon-button.js';
  import '@material/web/icon/icon.js';
  import { API } from '../lib/api';
  import '@material/web/dialog/dialog.js';
  import '@material/web/button/text-button.js';

  onMount(() => {
    store.loadStatus();
  });
  
  let displayPartitions = $derived([...new Set([...BUILTIN_PARTITIONS, ...(store.config?.partitions || [])])]);
  let storageLabel = $derived(store.storage?.type === 'tmpfs' ? store.systemInfo?.mountBase : store.L?.status?.storageDesc);
  let mountedCount = $derived(store.modules?.filter(m => m.is_mounted).length ?? 0);
  let showRebootConfirm = $state(false);
  
  function getDiagColor(level: string) {
      if (level === 'Critical') return 'var(--md-sys-color-error)';
      if (level === 'Warning') return 'var(--md-sys-color-tertiary)';
      return 'var(--md-sys-color-primary)';
  }

  function getDiagLabel(level: string) {
      if (level === 'Critical') return store.L?.status?.diagCritical ??
      level;
      if (level === 'Warning') return store.L?.status?.diagWarning ?? level;
      return store.L?.status?.diagInfo ?? level;
  }

  function getStoragePercent() {
    if (!store.storage?.percent) return 0;
    return parseFloat(store.storage.percent) / 100;
  }
</script>

<md-dialog 
  open={showRebootConfirm} 
  onclose={() => showRebootConfirm = false}
  style="--md-dialog-scrim-color: transparent; --md-sys-color-scrim: transparent;"
>
  <div slot="headline">{store.L?.common?.rebootTitle ?? 'Reboot System?'}</div>
  <div slot="content">
    {store.L?.common?.rebootConfirm ??
    'Are you sure you want to reboot the device?'}
  </div>
  <div slot="actions">
    <md-text-button 
      onclick={() => showRebootConfirm = false}
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      {store.L?.common?.cancel ??
      'Cancel'}
    </md-text-button>
    <md-text-button 
      onclick={() => { showRebootConfirm = false;
      API.reboot(); }}
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      {store.L?.common?.reboot ??
      'Reboot'}
    </md-text-button>
  </div>
</md-dialog>

<div class="dashboard-grid">
  <div class="storage-card">
    {#if store.loading.status}
      <div class="storage-header-row">
        <div style="display: flex; flex-direction: column; gap: 8px;">
            <Skeleton width="100px" height="24px" />
            <Skeleton width="60px" height="20px" borderRadius="12px" />
        </div>
        <Skeleton width="120px" height="64px" />
      </div>
      <div class="progress-container">
 
       <md-linear-progress indeterminate></md-linear-progress>
      </div>
      <div class="storage-details">
        <Skeleton width="150px" height="12px" />
        <Skeleton width="80px" height="12px" />
      </div>
    {:else}
      <div class="storage-header-row">
        <div class="storage-info-col">
            <div class="storage-label-group">
                <div class="storage-icon-circle">
 
                   <svg viewBox="0 0 24 24"><path d={ICONS.storage} /></svg>
                </div>
                <span class="storage-title">{store.L?.status?.storageTitle ??
                'Storage'}</span>
            </div>
            {#if store.storage?.type && store.storage.type !== 'unknown'}
              <span class="storage-type-badge {store.storage.type === 'tmpfs' ? 'type-tmpfs' : 'type-ext4'}">
                {store.storage.type?.toUpperCase()}
              </span>
             {/if}
      
         </div>
        <div class="storage-value-group">
            <span class="storage-value">{store.storage?.percent ??
            '0%'}</span>
            <span class="storage-unit">{store.L?.common?.used ??
            'Used'}</span>
        </div>
      </div>
      
      <div class="progress-container">
        <md-linear-progress value={getStoragePercent()}></md-linear-progress>
      </div>

      <div class="storage-details">
        <span class="detail-path">{storageLabel ??
        ''}</span>
        <span class="detail-nums">{store.storage?.used} / {store.storage?.size}</span>
      </div>
    {/if}
  </div>

  <div class="stats-row">
    <div class="stat-card">
      {#if store.loading.status}
        <Skeleton width="40px" height="32px" />
        <Skeleton width="60px" height="12px" style="margin-top: 8px" />
      {:else}
        <div class="stat-value">{mountedCount}</div>
        <div class="stat-label">{store.L?.status?.moduleActive ??
        'Active Modules'}</div>
      {/if}
    </div>
    <div class="stat-card">
      {#if store.loading.status}
         <Skeleton width="40px" height="32px" />
         <Skeleton width="60px" height="12px" style="margin-top: 8px" />
      {:else}
         <div class="stat-value">{store.config?.mountsource ??
         '-'}</div>
         <div class="stat-label">{store.L?.config?.mountSource ??
         'Mount Source'}</div>
      {/if}
    </div>
  </div>

  <div class="mode-card">
    <div class="mode-title">{store.L?.status?.activePartitions ??
    'Partitions'}</div>
    
    {#if store.loading.status}
      <div class="partition-grid">
        {#each Array(4) as _}
          <Skeleton width="60px" height="32px" borderRadius="8px" />
        {/each}
      </div>
    {:else}
      <md-chip-set class="partition-chips">
        {#each displayPartitions as part}
          <md-filter-chip 
            label={part} 
            selected={(store.activePartitions || []).includes(part)}
            elevated
          ></md-filter-chip>
        {/each}
      </md-chip-set>
    {/if}
  </div>

  <div class="mode-card">
    <div class="mode-title">{store.L?.status?.sysInfoTitle ??
    'System Info'}</div>
    <div class="info-grid">
      <div class="info-item">
        <span class="info-label">{store.L?.status?.kernel ??
        'Kernel'}</span>
        {#if store.loading.status}
          <Skeleton width="80%" height="16px" />
        {:else}
          <span class="info-val">{store.systemInfo?.kernel ||
          '-'}</span>
        {/if}
      </div>
      <div class="info-item">
        <span class="info-label">{store.L?.status?.selinux ??
        'SELinux'}</span>
        {#if store.loading.status}
          <Skeleton width="40%" height="16px" />
        {:else}
          <span class="info-val">{store.systemInfo?.selinux ||
          '-'}</span>
        {/if}
      </div>
      <div class="info-item full-width">
        <span class="info-label">{store.L?.status?.mountBase ??
        'Mount Base'}</span>
        {#if store.loading.status}
          <Skeleton width="90%" height="16px" />
        {:else}
          <span class="info-val mono">{store.systemInfo?.mountBase ??
          '-'}</span>
        {/if}
      </div>
    </div>
  </div>

  <div class="mode-card">
    <div class="mode-title" style="margin-bottom: 8px;">{store.L?.status?.modeStats ??
    'Mode Stats'}</div>
    {#if store.loading.status}
      <div class="skeleton-group">
        <Skeleton width="100%" height="20px" />
        <Skeleton width="100%" height="20px" />
        <Skeleton width="100%" height="20px" />
      </div>
    {:else}
      <div class="mode-row">
        <div class="mode-name">
          <div class="dot" style="background-color: var(--md-sys-color-secondary)"></div>
          {store.L?.status?.modeAuto ??
          'Auto'}
        </div>
        <span class="mode-count">{store.modeStats?.auto ??
        0}</span>
      </div>
      <div class="mode-divider"></div>
      <div class="mode-row">
        <div class="mode-name">
          <div class="dot" style="background-color: var(--md-sys-color-tertiary)"></div>
          {store.L?.status?.modeMagic ??
          'Magic'}
        </div>
        <span class="mode-count">{store.modeStats?.magic ??
        0}</span>
      </div>
    {/if}
  </div>

  <div class="mode-card">
      <div class="mode-title">{store.L?.status?.health ??
      'System Health'}</div>
      {#if store.loading.diagnostics}
        <div class="skeleton-group">
            <Skeleton width="100%" height="20px" />
            <Skeleton width="80%" height="20px" />
        </div>
      {:else if store.diagnostics.length === 0}
        <div class="health-message healthy">{store.L?.status?.healthy ??
        'All checks passed.'}</div>
      {:else}
        <div class="diagnostic-list">
            {#each store.diagnostics as issue}
                <div class="diagnostic-item">
                    <div class="diag-level" style="color: {getDiagColor(issue.level)}">
                        {getDiagLabel(issue.level)}
                    </div>
                    <div class="diag-content">
                        <div class="diag-context">{issue.context}</div>
                        <div class="diag-message">{issue.message}</div>
                    </div>
                </div>
            {/each}
        </div>
      {/if}
  </div>
</div>

<BottomActions>
  <div class="spacer"></div>
  <div style="display: flex; gap: 8px; align-items: center;">
    <md-filled-tonal-icon-button 
      class="reboot-btn"
      onclick={() => showRebootConfirm = true}
      title="Reboot"
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      <md-icon>
        <svg viewBox="0 0 24 24"><path d={ICONS.power} /></svg>
      </md-icon>
    </md-filled-tonal-icon-button>
    
    <md-filled-tonal-icon-button 
      onclick={() => store.loadStatus()} 
      disabled={store.loading.status}
      title={store.L?.logs?.refresh}
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      <md-icon>
        <svg viewBox="0 0 24 24"><path d={ICONS.refresh} /></svg>
      </md-icon>
    </md-filled-tonal-icon-button>
  </div>
</BottomActions>

// webui/src/routes/StatusTab.tsx
/**
 * Copyright 2026 Hybrid Mount Developers
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { createMemo, createSignal, onMount, Show, For } from "solid-js";
import { uiStore } from "../lib/stores/uiStore";
import { sysStore } from "../lib/stores/sysStore";
import { configStore } from "../lib/stores/configStore";
import { moduleStore } from "../lib/stores/moduleStore";
import { ICONS } from "../lib/constants";
import { BUILTIN_PARTITIONS } from "../lib/constants_gen";
import Skeleton from "../components/Skeleton";
import BottomActions from "../components/BottomActions";
import { API } from "../lib/api";
import "./StatusTab.css";

import "@material/web/iconbutton/filled-tonal-icon-button.js";
import "@material/web/icon/icon.js";
import "@material/web/dialog/dialog.js";
import "@material/web/button/text-button.js";
import "@material/web/ripple/ripple.js";

export default function StatusTab() {
  onMount(() => {
    sysStore.loadStatus();
  });

  const displayPartitions = createMemo(() => [
    ...new Set([
      ...BUILTIN_PARTITIONS,
      ...(configStore.config?.partitions || []),
    ]),
  ]);

  const mountedCount = createMemo(
    () => moduleStore.modules?.filter((m) => m.is_mounted).length ?? 0,
  );

  const [showRebootConfirm, setShowRebootConfirm] = createSignal(false);

  function getModeDisplayName(mode: string | null | undefined) {
    if (!mode) return "Unknown";
    const key = `mode_${mode}` as keyof typeof uiStore.L.config;
    return uiStore.L.config?.[key] || mode.toUpperCase();
  }

  const modeDistribution = createMemo(() => {
    const stats = moduleStore.modeStats;
    const total = (stats?.auto || 0) + (stats?.magic || 0);
    if (total === 0) return { auto: 0, magic: 0 };
    return {
      auto: (stats.auto / total) * 100,
      magic: (stats.magic / total) * 100,
    };
  });

  return (
    <>
      <md-dialog
        open={showRebootConfirm()}
        onclose={() => setShowRebootConfirm(false)}
        class="transparent-scrim"
      >
        <div slot="headline">
          {uiStore.L?.common?.rebootTitle ?? "Reboot System?"}
        </div>
        <div slot="content">
          {uiStore.L?.common?.rebootConfirm ??
            "Are you sure you want to reboot the device?"}
        </div>
        <div slot="actions">
          <md-text-button onClick={() => setShowRebootConfirm(false)}>
            {uiStore.L?.common?.cancel ?? "Cancel"}
          </md-text-button>
          <md-text-button
            onClick={() => {
              setShowRebootConfirm(false);
              API.reboot();
            }}
          >
            {uiStore.L?.common?.reboot ?? "Reboot"}
          </md-text-button>
        </div>
      </md-dialog>

      <div class="dashboard-grid">
        <div class="hero-card">
          <Show
            when={!sysStore.loading}
            fallback={
              <div class="skeleton-col">
                <Skeleton width="40%" height="24px" />
                <Skeleton width="80%" height="48px" />
                <Skeleton width="60%" height="20px" />
              </div>
            }
          >
            <div class="hero-content">
              <span class="hero-label">
                {uiStore.L?.status?.storageTitle ?? "Backend Strategy"}
              </span>
              <span class="hero-value">
                {getModeDisplayName(sysStore.storage?.type)}
              </span>
            </div>

            <div class="mount-base-chip">
              <md-icon
                style={{
                  "font-size": "14px",
                  width: "14px",
                  height: "14px",
                  opacity: 0.7,
                }}
              >
                <svg viewBox="0 0 24 24">
                  <path d={ICONS.mount_path} />
                </svg>
              </md-icon>
              <span class="mount-base-text">
                {sysStore.systemInfo?.mountBase || "Unknown"}
              </span>
            </div>
          </Show>
        </div>

        <div class="metrics-row">
          <div class="metric-card">
            <Show
              when={!sysStore.loading}
              fallback={<Skeleton width="50%" height="32px" />}
            >
              <div class="metric-icon-bg">
                <svg viewBox="0 0 24 24">
                  <path d={ICONS.modules} />
                </svg>
              </div>
              <span class="metric-value">{mountedCount()}</span>
              <span class="metric-label">
                {uiStore.L?.status?.moduleActive ?? "Active Modules"}
              </span>
            </Show>
          </div>

          <div class="metric-card">
            <Show
              when={!sysStore.loading}
              fallback={<Skeleton width="50%" height="32px" />}
            >
              <div class="metric-icon-bg">
                <svg viewBox="0 0 24 24">
                  <path d={ICONS.ksu} />
                </svg>
              </div>
              <span class="metric-value">
                {configStore.config?.mountsource || "-"}
              </span>
              <span class="metric-label">
                {uiStore.L?.config?.mountSource ?? "Mount Source"}
              </span>
            </Show>
          </div>
        </div>

        <div class="mode-stats-card">
          <div class="card-title">
            {uiStore.L?.status?.modeStats ?? "Mode Distribution"}
          </div>
          <Show
            when={!sysStore.loading}
            fallback={
              <Skeleton width="100%" height="24px" borderRadius="12px" />
            }
          >
            <div class="stats-bar-container">
              <div
                class="bar-segment bar-auto"
                style={{ width: `${modeDistribution().auto}%` }}
              ></div>
              <div
                class="bar-segment bar-magic"
                style={{ width: `${modeDistribution().magic}%` }}
              ></div>
            </div>
            <div class="stats-legend">
              <div class="legend-item">
                <div class="legend-dot dot-auto"></div>
                <span>Overlay: {moduleStore.modeStats?.auto || 0}</span>
              </div>
              <div class="legend-item">
                <div class="legend-dot dot-magic"></div>
                <span>Magic: {moduleStore.modeStats?.magic || 0}</span>
              </div>
            </div>
          </Show>
        </div>

        <div class="info-card">
          <div class="card-title">
            {uiStore.L?.status?.sysInfoTitle ?? "System Info"}
          </div>

          <div class="info-row">
            <span class="info-key">
              {uiStore.L?.status?.kernel ?? "Kernel"}
            </span>
            <Show
              when={!sysStore.loading}
              fallback={<Skeleton width="100px" height="16px" />}
            >
              <span class="info-val">{sysStore.systemInfo?.kernel || "-"}</span>
            </Show>
          </div>

          <div class="info-row">
            <span class="info-key">
              {uiStore.L?.status?.selinux ?? "SELinux"}
            </span>
            <Show
              when={!sysStore.loading}
              fallback={<Skeleton width="60px" height="16px" />}
            >
              <span class="info-val">
                {sysStore.systemInfo?.selinux || "-"}
              </span>
            </Show>
          </div>

          <div class="card-title" style={{ "margin-top": "8px" }}>
            {uiStore.L?.status?.activePartitions ?? "Partitions"}
          </div>

          <div class="partition-list">
            <Show
              when={!sysStore.loading}
              fallback={<Skeleton width="100%" height="32px" />}
            >
              <For each={displayPartitions()}>
                {(part) => (
                  <div
                    class={`partition-chip ${(sysStore.activePartitions || []).includes(part) ? "active" : ""}`}
                  >
                    {part}
                  </div>
                )}
              </For>
            </Show>
          </div>
        </div>
      </div>

      <BottomActions>
        <div class="spacer"></div>
        <div class="action-row">
          <md-filled-tonal-icon-button
            class="reboot-btn"
            onClick={() => setShowRebootConfirm(true)}
            title="Reboot"
            role="button"
            tabIndex={0}
          >
            <md-icon>
              <svg viewBox="0 0 24 24">
                <path d={ICONS.power} />
              </svg>
            </md-icon>
          </md-filled-tonal-icon-button>

          <md-filled-tonal-icon-button
            onClick={() => sysStore.loadStatus()}
            disabled={sysStore.loading}
            title={uiStore.L?.logs?.refresh}
            role="button"
            tabIndex={0}
          >
            <md-icon>
              <svg viewBox="0 0 24 24">
                <path d={ICONS.refresh} />
              </svg>
            </md-icon>
          </md-filled-tonal-icon-button>
        </div>
      </BottomActions>
    </>
  );
}
